GradesWebApplication/Models/Student.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public string StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }
    }
}

GradesWebApplication/ViewModels/StudentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GradesWebApplication.ViewModels
{
    public class StudentViewModel
    {
        public List<string> ListofSubjects { get; set; }

        //Student
        public string StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }

        //Grade
        public string SubjectID { get; set; }
        public Nullable<decimal> Grade1 { get; set; }

    }
}

GradesWebApplication/Controllers/DownloadController.cs
using GradesWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GradesWebApplication.Controllers
{
    [HandleError(ExceptionType = typeof(MetadataException), View = "MetaError", Order = 4)]
    [HandleError(ExceptionType = typeof(SqlException), View = "SqlError", Order = 3)]
    [HandleError(ExceptionType = typeof(EntityException), View = "EntityError", Order = 2)]
    [HandleError(ExceptionType = typeof(NullReferenceException), View = "Error", Order = 1)]
    [HandleError(ExceptionType = typeof(Exception), View = "Error", Order = 0)]
    public class DownloadController : Controller
    {
        Reporting _report = new Reporting();

        // GET: Download
        public ActionResult Index()
        {
            return View();
        }

        public FileContentResult StudentCSV(string studentid)
        {
            string csv = _report.StudentReport(studentid);

            if (String.IsNullOrEmpty(csv))
            {
                ViewBag.Error = _report.ErrMessage;
                RedirectToRoute("ReportError");
            }
            
            return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", studentid + " " + "Student Report.csv");            
        }

        public FileContentResult SubjectCSV(string subjectid)
        {
            string csv = _report.SubjectReport(subjectid);

            if (String.IsNullOrEmpty(csv))
            {
                ViewBag.Error = _report.ErrMessage;
                RedirectToRoute("ReportError");
            }

            return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", subjectid + " " + "Subject Report.csv");
        }
    }
}

GradesWebApplication/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GradesWebApplication.Models;
using System.Data.Entity.Core;
using System.Data.SqlClient;

namespace GradesWebApplication.Controllers
{
    [HandleError(ExceptionType = typeof(MetadataException), View = "MetaError", Order = 4)]
    [HandleError(ExceptionType = typeof(SqlException), View = "SqlError", Order = 3)]
    [HandleError(ExceptionType = typeof(EntityException), View = "EntityError", Order = 2)]
    [HandleError(ExceptionType = typeof(NullReferenceException), View = "Error", Order = 1)]
    [HandleError(ExceptionType = typeof(Exception), View = "Error", Order = 0)]
    public class GradesController : Controller
    {
        private StudentManagementSystemEntities db = new StudentManagementSystemEntities();


        // GET: Grades/Create
        public ActionResult Create(string studentid)
        {
            ViewBag.Sid = studentid;

            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentID", studentid);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName");
            //return View();
            return View();
        }

        // POST: Grades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,SubjectID,Grade1,DateEntered,StudentID")] Grade grade)
        {
            ViewBag.Sid = grade.StudentID;
            grade.DateEntered = DateTime.Now;

            if (ModelState.IsValid)
            {
                if (db.Grades.Any(g => g.StudentID.Equals(grade.StudentID) && g.SubjectID.Equals(grade.SubjectID)))
                    ViewBag.Error = "Student already taking this subject";
                else
                {
                    db.Grades.Add(grade);
                    db.SaveChanges();
                    return RedirectToAction("Details", "Students", new { id = grade.StudentID });
                }
            }

            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentID", grade.StudentID);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", grade.SubjectID);
            return View(grade);
            
        }

        // GET: Grades/Edit/5
        public ActionResult Edit(int? id)
        {
            

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = db.Grades.Find(id);
            ViewBag.Sid = grade.StudentID;
            if (grade == null)
            {
                return HttpNotFound();
            }
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentID", grade.StudentID);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", grade.SubjectID);
            return View(grade);
        }

        // POST: Grades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,SubjectID,Grade1,DateEntered,StudentID")] Grade grade)
        {
            grade.DateEntered = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Entry(grade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Students", new { id = grade.StudentID });
            }
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentID", grade.StudentID);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", grade.SubjectID);
            return View(grade);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GradesWebApplication/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GradesWebApplication.Models;
using GradesWebApplication.ViewModels;
using PagedList;
using System.Data.Entity.Core;
using System.Data.SqlClient;

namespace GradesWebApplication.Controllers
{
    [HandleError(ExceptionType = typeof(MetadataException), View = "MetaError", Order = 4)]
    [HandleError(ExceptionType = typeof(SqlException), View = "SqlError", Order = 3)]
    [HandleError(ExceptionType = typeof(EntityException), View = "EntityError", Order = 2)]
    [HandleError(ExceptionType = typeof(NullReferenceException), View = "Error", Order = 1)]
    [HandleError(ExceptionType = typeof(Exception), View = "Error", Order = 0)]
    public class StudentsController : Controller
    {
        private StudentManagementSystemEntities db = new StudentManagementSystemEntities();

        // GET: Students
        public ActionResult Index(string sortOrder, string option, string searchString, string currentFilter, int? page)
        {
            //return View(db.Students.ToList());

            ViewBag.CurrentSort = sortOrder;
            ViewBag.studentidSortParm = String.IsNullOrEmpty(sortOrder) ? "studentid_desc" : "";
            ViewBag.firstnameSortParm = sortOrder == "firstname" ? "firstname_desc" : "firstname";
            ViewBag.lastnameSortParm = sortOrder == "lastname" ? "lastname_desc" : "lastname";
            ViewBag.dobSortParm = sortOrder == "dob" ? "dob_desc" : "dob";
            ViewBag.addressSortParm = sortOrder == "address" ? "address_desc" : "address";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var details = from d in db.Students select d;

            if (!String.IsNullOrEmpty(searchString))
            {
                if (option == "StudentID")
                {
                    details = details.Where(d => d.StudentID.StartsWith(searchString));
                }
                else if (option == "FirstName")
                {
                    details = details.Where(d => d.FirstName.StartsWith(searchString));
                }
                else
                {
                    details = details.Where(d => d.LastName.StartsWith(searchString));
                }
            }

            switch (sortOrder)
            {
                case "studentid_desc":
                    details = details.OrderByDescending(d => d.StudentID);
                    break;
                case "firstname":
                    details = details.OrderBy(d => d.FirstName);
                    break;
                case "firstname_desc":
                    details = details.OrderByDescending(d => d.FirstName);
                    break;
                case "lastname":
                    details = details.OrderBy(d => d.LastName);
                    break;
                case "lastname_desc":
                    details = details.OrderByDescending(d => d.LastName);
                    break;
                case "dob":
                    details = details.OrderBy(d => d.DateOfBirth);
                    break;
                case "dob_desc":
                    details = details.OrderByDescending(d => d.DateOfBirth);
                    break;
                case "address":
                    details = details.OrderBy(d => d.Address);
                    break;
                case "address_desc":
                    details = details.OrderByDescending(d => d.Address);
                    break;
                default:
                    details = details.OrderBy(d => d.StudentID);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(details.ToPagedList(pageNumber, pageSize));

            ///VIEWMODEL CODE

            //List<StudentViewModel> StudentVMlist = new List<StudentViewModel>();

            //var studentlist = (from s in db.Students
            //                   join g in db.Grades on s.StudentID equals g.StudentID
            //                   select new { s.StudentID, s.FirstName, s.LastName, s.Address, g.Grade1 }).ToList();

            //foreach (var item in studentlist)
            //{
            //    StudentViewModel stvm = new StudentViewModel();

            //    stvm.StudentID = item.StudentID;
            //    stvm.FirstName = item.FirstName;
            //    stvm.LastName = item.LastName;
            //    stvm.Address = item.Address;
            //    stvm.Grade1 = item.Grade1;
            //    StudentVMlist.Add(stvm);
            //}
            //return View(StudentVMlist);



        }

        // GET: Students/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentID,FirstName,LastName,DateOfBirth,Address,DateEntered")] Student student)
        {
            student.DateEntered = DateTime.Now;
            student.StudentID = CreateStudentId();

            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentID,FirstName,LastName,DateOfBirth,Address,DateEntered")] Student student)
        {
            student.DateEntered = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private string CreateStudentId()
        {
            Random r = new Random();
            int idNumber = r.Next(0, 9999999);

            string wholeId = "ST" + idNumber;

            return wholeId;
        }
    }
}

GradesWebApplication/Views/Students/Create.cshtml
@model GradesWebApplication.Models.Student

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.DateEntered, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateEntered, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateEntered, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GradesWebApplication/Views/Students/Details.cshtml
@model GradesWebApplication.Models.Student

@{
    ViewBag.Title = "Details";
}

<h2>Student</h2>

<script src="~/scripts/jquery-1.10.2.min.js"></script>
<script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.DateEntered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateEntered)
        </dd>*@

    </dl>

    <table class="table">
        <tr>
            <th>
                Subject ID
            </th>
            <th>
                Subject
            </th>
            <th>
                Grade
            </th>
            <th>
                @Html.ActionLink("Add Subject", "Create", "Grades", new { studentid = Model.StudentID }, null)
                @*@Ajax.ActionLink("Add Subject", "Create", "Grades", new { studentid = Model.StudentID }, new AjaxOptions()
           {
               HttpMethod = "Get",
               UpdateTargetId = "divDetails",
               InsertionMode = InsertionMode.Replace
           })*@
            </th>
        </tr>

        @foreach (var item in Model.Grades)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SubjectID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject.SubjectName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade1)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Grades", new { id = item.ID }, null) 
                    @*@Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
                </td>
            </tr>
        }
    </table>
</div>

<p>
    @*@Html.ActionLink("Create New", "Create") |
    @Html.ActionLink("Edit", "Edit", new { id = Model.StudentID }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

<div id="divDetails"> </div>

GradesWebApplication/Views/Students/Edit.cshtml
@model GradesWebApplication.Models.Student

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.DateEntered, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateEntered, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateEntered, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GradesWebApplication/Views/Students/Index.cshtml
@*@model IEnumerable<GradesWebApplication.Models.Student>*@
@*@model IEnumerable< GradesWebApplication.ViewModels.StudentViewModel>*@

@model PagedList.IPagedList<GradesWebApplication.Models.Student>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Students";
}

<h2>Students</h2>

<p>
    @Html.ActionLink("Create New Student", "Create")
</p>

@*@using (Html.BeginForm("Index", "Students", FormMethod.Get))
{
    <p>
        Find by ID: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}*@

@using (Html.BeginForm("Index", "Students", FormMethod.Get))
{
    //the following are search options
    <b> Search Option:  </b>@Html.RadioButton("option", "StudentID", true) <text> Student ID </text> @Html.RadioButton("option", "FirstName") <text> First Name </text>
    @Html.RadioButton("option", "LastName")<text> Last Name </text> @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
    <input type="submit" value="Search" />
}

<br />


<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Student ID", "Index", new { sortOrder = ViewBag.studentidSortParm, currentFilter = ViewBag.CurrentFilter })
            @*@Html.DisplayNameFor(model => model.StudentID)*@
        </th>
        <th>
            @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.firstnameSortParm, currentFilter = ViewBag.CurrentFilter })
            @*@Html.DisplayNameFor(model => model.FirstName)*@
        </th>
        <th>
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.lastnameSortParm, currentFilter = ViewBag.CurrentFilter })
            @*@Html.DisplayNameFor(model => model.LastName)*@
        </th>
        <th>
            @Html.ActionLink("Date Of Birth ", "Index", new { sortOrder = ViewBag.dobSortParm, currentFilter = ViewBag.CurrentFilter })
            @*@Html.DisplayNameFor(model => model.DateOfBirth)*@
        </th>
        <th>
            @Html.ActionLink("Address", "Index", new { sortOrder = ViewBag.addressSortParm, currentFilter = ViewBag.CurrentFilter })
            @*@Html.DisplayNameFor(model => model.Address)*@
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.DateEntered)
        </th>*@
        <th></th>
    </tr>

@if (Model.Count() == 0) {<tr> <td colspan = "3" >No records found.</td>
</tr > }

else
{

foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StudentID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.DateEntered)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.StudentID }) |
            @Html.ActionLink("Details", "Details", new { id = item.StudentID }) |
            @Html.ActionLink("Save Report", "StudentCSV", "Download", new { studentid = item.StudentID }, null) 
            @*@Html.ActionLink("Delete", "Delete", new { id=item.StudentID })*@
        </td>
    </tr>
   }
}

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))